services:
  db:
    image: postgres:15          # версия Postgres, можно указать другую
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"             # доступ к базе снаружи на 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_app
    restart: always
    ports:
      - "3000:3000"             # Metabase доступен на http://localhost:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
    depends_on:
      - db                      # запускать после postgres

volumes:
  pgdata:
